//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigTag.DataModel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsLog : BaseEntity
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ActorPageId { get; set; }
        public Nullable<System.Guid> TargetId { get; set; }
        public Nullable<int> ActionCode { get; set; }
        public Nullable<System.Guid> OwnerPageId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CustomRelatedId { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual EventsLog EventsLog1 { get; set; }
        public virtual EventsLog EventsLog2 { get; set; }
        public virtual Page Page1 { get; set; }
    }
}
