//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigTag.DataModel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowCondition : BaseEntity
    {
        public System.Guid Id { get; set; }
        public System.Guid FollowId { get; set; }
        public System.Guid MenuId { get; set; }
    
        public virtual Follow Follow { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
