//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigTag.DataModel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu : BaseEntity
    {
        public Menu()
        {
            this.FollowConditions = new HashSet<FollowCondition>();
            this.FollowMenuPackages = new HashSet<FollowMenuPackage>();
        }
    
        public System.Guid Id { get; set; }
        public string MenuTitle { get; set; }
        public long Score { get; set; }
        public System.Guid PageId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<FollowCondition> FollowConditions { get; set; }
        public virtual ICollection<FollowMenuPackage> FollowMenuPackages { get; set; }
        public virtual Page Page { get; set; }
    }
}
