//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigTag.DataModel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : BaseEntity
    {
        public User()
        {
            this.FollowMenus = new HashSet<FollowMenu>();
            this.Pages = new HashSet<Page>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string ProfileInfo { get; set; }
        public Nullable<System.Guid> ProfileImageId { get; set; }
    
        public virtual ICollection<FollowMenu> FollowMenus { get; set; }
        public virtual ImageTable ImageTable { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
    }
}
